server:
  port: 8083

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/realestate_payment_db

app:
  api:
    key: my-super-secret-payment-api-key

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always